name: cordcloud

on:
  push:
    branches:
      - master
  schedule:
    - cron: "30 0 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v1

      - name: Auto green
        run: bash ./cordcloud
