  
name: cordcloud

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 21 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v1

      - name: Auto green
        run: |
            chmod 777 cordcloud
            ./cordcloud
